version: '2'
services:
  base:
    image: alpine
    working_dir: "/go/src/github.com/MYOB-Technology/dataform/"
    volumes:
    - ".:/go/src/github.com/MYOB-Technology/dataform/"
    - "${HOME}/.aws:/root/.aws"

  dep:
    extends:
      service: base
    image: myobplatform/go-dep:1.8
    entrypoint: dep

  go:
    extends:
      service: base
    image: golang:1.9-alpine
    entrypoint: go

  aws:
    extends:
      service: base
    image: cgswong/aws:aws

  goreleaser:
    extends:
      service: base
    image: myobplatform/goreleaser:0.32.0-alpine
    environment:
    - GITHUB_TOKEN
